name: MachineLearningForCAP
version: "2024.07-04"
license: "GPL-2.0-or-later"
date: 2024-07-09
description: |
    Exploring categorical machine learning in CAP

authors:
    - name: Kamal Saleh
      url: https://github.com/kamalsaleh

maintainers:
    - name: Kamal Saleh
      url: https://github.com/kamalsaleh

GAP: ">= 4.13.0"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "CAP"
      version: ">= 2023.12-05"
      url: "https://homalg-project.github.io/pkg/CAP"
    - name: "MonoidalCategories"
      version: ">= 2024.04-01"
      url: "https://homalg-project.github.io/pkg/MonoidalCategories"
    - name: "CartesianCategories"
      version: ">= 2024.04-01"
      url: "https://homalg-project.github.io/pkg/CartesianCategories"
    - name: "ToolsForCategoricalTowers"
      version: ">= 2024.06-02"
      url: "https://homalg-project.github.io/pkg/ToolsForCategoricalTowers"

suggested-pkgs:
    - name: "ToolsForHigherHomologicalAlgebra"
      version: ">= 2023.01-01"

www: https://homalg-project.github.io/pkg/MachineLearningForCAP
readme: README.md
packageinfo: https://homalg-project.github.io/MachineLearningForCAP/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/MachineLearningForCAP/releases/download/v2024.07-04/MachineLearningForCAP-2024.07-04.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/MachineLearningForCAP/releases/download/v2024.07-04/MachineLearningForCAP-2024.07-04.zip

pdf: https://github.com/homalg-project/MachineLearningForCAP/releases/download/v2024.07-04/MachineLearningForCAP-2024.07-04-manual.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    Explore Categorical Machine Learning.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Sal09</span>]   <b class='BibAuthor'>Saleh, K.</b>,
     <i class='BibTitle'>MachineLearningForCAP, Exploring categorical machine learning in CAP,
             Version 2024.07-04</i>
     (<span class='BibYear'>7-09</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/MachineLearningForCAP">https://homalg-project.github.io/pkg/MachineLearningForCAP</a></span>.
    </p>
    

bibtex: |
    @misc{ MachineLearningForCAP,
      author =           {Saleh, K.},
      title =            {{MachineLearningForCAP}, Exploring categorical machine
                          learning           in          CAP,          {V}ersion
                          2024.07\texttt{\symbol{45}}04},
      month =            {4\texttt{\symbol{45}}},
      year =             {7\texttt{\symbol{45}}09},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/pkg/MachineLearningForCAP}
                          {\texttt{https://homalg\texttt{\symbol{45}}project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{MachineLearningForCAP}}},
      keywords =         {Explore Categorical Machine Learning},
      printedkey =       {Sal09}
    }

