# SPDX-License-Identifier: GPL-2.0-or-later
# MachineLearningForCAP: Exploring categorical machine learning in CAP
#
# Declarations
#
# THIS FILE IS AUTOMATICALLY GENERATED, SEE CAP_project/CAP/gap/MethodRecord.gi

#! @Chapter operations for machine learning in CAP

#! @Section Add-methods

#! @Description
#! The arguments are a category $C$ and a function $F$.
#! This operation adds the given function $F$
#! to the category for the basic operation `MultiplicationForMorphisms`.
#! $F: ( alpha, beta ) \mapsto \mathtt{MultiplicationForMorphisms}(alpha, beta)$.
#! @Returns nothing
#! @Arguments C, F
DeclareOperation( "AddMultiplicationForMorphisms",
                  [ IsCapCategory, IsFunction ] );

DeclareOperation( "AddMultiplicationForMorphisms",
                  [ IsCapCategory, IsFunction, IsInt ] );

DeclareOperation( "AddMultiplicationForMorphisms",
                  [ IsCapCategory, IsList, IsInt ] );

DeclareOperation( "AddMultiplicationForMorphisms",
                  [ IsCapCategory, IsList ] );

#! @Description
#! The arguments are a category $C$ and a function $F$.
#! This operation adds the given function $F$
#! to the category for the basic operation `ReverseDifferential`.
#! $F: ( alpha ) \mapsto \mathtt{ReverseDifferential}(alpha)$.
#! @Returns nothing
#! @Arguments C, F
DeclareOperation( "AddReverseDifferential",
                  [ IsCapCategory, IsFunction ] );

DeclareOperation( "AddReverseDifferential",
                  [ IsCapCategory, IsFunction, IsInt ] );

DeclareOperation( "AddReverseDifferential",
                  [ IsCapCategory, IsList, IsInt ] );

DeclareOperation( "AddReverseDifferential",
                  [ IsCapCategory, IsList ] );

#! @Description
#! The arguments are a category $C$ and a function $F$.
#! This operation adds the given function $F$
#! to the category for the basic operation `ReverseDifferentialWithGivenObjects`.
#! $F: ( source, alpha, range ) \mapsto \mathtt{ReverseDifferentialWithGivenObjects}(source, alpha, range)$.
#! @Returns nothing
#! @Arguments C, F
DeclareOperation( "AddReverseDifferentialWithGivenObjects",
                  [ IsCapCategory, IsFunction ] );

DeclareOperation( "AddReverseDifferentialWithGivenObjects",
                  [ IsCapCategory, IsFunction, IsInt ] );

DeclareOperation( "AddReverseDifferentialWithGivenObjects",
                  [ IsCapCategory, IsList, IsInt ] );

DeclareOperation( "AddReverseDifferentialWithGivenObjects",
                  [ IsCapCategory, IsList ] );
